# This file was generated by GoReleaser. DO NOT EDIT.
cask "dutils" do
  version "1.0.2"

  on_macos do
    on_intel do
      url "https://github.com/lukasmay/dutils/releases/download/v#{version}/dutils_Darwin_x86_64.tar.gz"
      sha256 "b061d6a887be71f58d5c8db52709e87992788ea08b7cfb7336aae725a992e7bf"
    end
    on_arm do
      url "https://github.com/lukasmay/dutils/releases/download/v#{version}/dutils_Darwin_arm64.tar.gz"
      sha256 "41e027d1b3c573b77add638ad482086c857f09271229ee4858d5f60886096458"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/lukasmay/dutils/releases/download/v#{version}/dutils_Linux_x86_64.tar.gz"
      sha256 "b6d778136d8ddeb817ebb2e733bae2fd2a18fc2523f239e397c9f9fc711b08b3"
    end
    on_arm do
      url "https://github.com/lukasmay/dutils/releases/download/v#{version}/dutils_Linux_arm64.tar.gz"
      sha256 "4ae4feabf234fbffc0d0653f61d37b45a42246f930c0ec39e02df2862090361e"
    end
  end

  name "dutils"
  desc "Docker and Docker Compose workflow simplifier"
  homepage "https://github.com/lukasmay/dutils"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dutils"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dutils"]
    end
  end

  # No zap stanza required

end
