# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dutils < Formula
  desc "Docker and Docker Compose workflow simplifier"
  homepage "https://github.com/lukasmay/dutils"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukasmay/dutils/releases/download/v1.0.0/dutils_Darwin_x86_64.tar.gz"
      sha256 "5c07b14ad2fe9f6dd68ebe77fe766fd46205731ea36140d0b0c4ed6124d867f3"

      define_method(:install) do
        bin.install "dutils"

        # Generate shell completions
        (bash_completion/"dutils").write `#{bin}/dutils completion bash`
        (zsh_completion/"_dutils").write `#{bin}/dutils completion zsh`
        (fish_completion/"dutils.fish").write `#{bin}/dutils completion fish`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukasmay/dutils/releases/download/v1.0.0/dutils_Darwin_arm64.tar.gz"
      sha256 "3264b3dccdbed695e978faff7064ecb7ebce28c9bfe7edd22ebef50c7fdd5399"

      define_method(:install) do
        bin.install "dutils"

        # Generate shell completions
        (bash_completion/"dutils").write `#{bin}/dutils completion bash`
        (zsh_completion/"_dutils").write `#{bin}/dutils completion zsh`
        (fish_completion/"dutils.fish").write `#{bin}/dutils completion fish`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukasmay/dutils/releases/download/v1.0.0/dutils_Linux_x86_64.tar.gz"
      sha256 "54984c6fd6fed9c0f6403bf9faa6cb2d12f949b5e622681a77a613c2423e62d0"
      define_method(:install) do
        bin.install "dutils"

        # Generate shell completions
        (bash_completion/"dutils").write `#{bin}/dutils completion bash`
        (zsh_completion/"_dutils").write `#{bin}/dutils completion zsh`
        (fish_completion/"dutils.fish").write `#{bin}/dutils completion fish`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukasmay/dutils/releases/download/v1.0.0/dutils_Linux_arm64.tar.gz"
      sha256 "c0b9af1e2a466c3c9dcacebc7210821d1d8e7026d675514f4f7552001fe345b3"
      define_method(:install) do
        bin.install "dutils"

        # Generate shell completions
        (bash_completion/"dutils").write `#{bin}/dutils completion bash`
        (zsh_completion/"_dutils").write `#{bin}/dutils completion zsh`
        (fish_completion/"dutils.fish").write `#{bin}/dutils completion fish`
      end
    end
  end

  test do
    system "#{bin}/dutils version"
  end
end
