# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Dutils < Formula
  desc "Docker and Docker Compose workflow simplifier"
  homepage "https://github.com/lukasmay/dutils"
  version "1.0.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/lukasmay/dutils/releases/download/v1.0.1/dutils_Darwin_x86_64.tar.gz"
      sha256 "5d102e532530a52eebd6018258a94c90616d94204dec4418c475965305abb991"

      define_method(:install) do
        bin.install "dutils"

        # Generate shell completions
        (bash_completion/"dutils").write `#{bin}/dutils completion bash`
        (zsh_completion/"_dutils").write `#{bin}/dutils completion zsh`
        (fish_completion/"dutils.fish").write `#{bin}/dutils completion fish`
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/lukasmay/dutils/releases/download/v1.0.1/dutils_Darwin_arm64.tar.gz"
      sha256 "80fba077628dd4120b72f1b8f35802c3f5082bb47933cd21dfa1a627c9052c1f"

      define_method(:install) do
        bin.install "dutils"

        # Generate shell completions
        (bash_completion/"dutils").write `#{bin}/dutils completion bash`
        (zsh_completion/"_dutils").write `#{bin}/dutils completion zsh`
        (fish_completion/"dutils.fish").write `#{bin}/dutils completion fish`
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukasmay/dutils/releases/download/v1.0.1/dutils_Linux_x86_64.tar.gz"
      sha256 "0ba3b70ad26ad3c5756a3f4a5a2b7ca044f3b16f30b4068ffe758336883c3505"
      define_method(:install) do
        bin.install "dutils"

        # Generate shell completions
        (bash_completion/"dutils").write `#{bin}/dutils completion bash`
        (zsh_completion/"_dutils").write `#{bin}/dutils completion zsh`
        (fish_completion/"dutils.fish").write `#{bin}/dutils completion fish`
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lukasmay/dutils/releases/download/v1.0.1/dutils_Linux_arm64.tar.gz"
      sha256 "de175c56ce1dae912c34f029f058b4d18c03a5fcaed92c851c8fe703f3e5a455"
      define_method(:install) do
        bin.install "dutils"

        # Generate shell completions
        (bash_completion/"dutils").write `#{bin}/dutils completion bash`
        (zsh_completion/"_dutils").write `#{bin}/dutils completion zsh`
        (fish_completion/"dutils.fish").write `#{bin}/dutils completion fish`
      end
    end
  end

  test do
    system "#{bin}/dutils version"
  end
end
